### ISSUE TITLE
How to change color and set symbol bold

### ISSUE THREAD

**Issue by robaxelsen** [pablopunk/bashy#9]
First off, thanks a lot for this awesome prompt. Love it 💙

I've managed to change the color of the foreground symbol to green, but I am struggling with the following:

~- How to set symbol to bold~
- How to add color to repo and branch text

I am grateful for any help with this. Thanks in advance!

**EDIT:** Seems the bold was already there, just not clearly visible in Tilda terminal. In Gnome terminal it works well.

**Comment by pablopunk** [comment]
Hi! Thanks for the feedback!

Well I would do something like this:

```sh
cyan="\x01\033[36m\x02"
echo -en "$cyan$bold$repo$normal at $cyan$bold$branch $symbols$normal"
```

You can see [here](https://misc.flogisoft.com/bash/tip_colors_and_formatting) a list of colors and the code you have to write (in my case, `cyan=36`). Keep in mind that you have to write the whole `\x01\033[36m\x02` because the small notation (`\e[36m`) can cause a [bug](https://github.com/pablopunk/bashy/issues/4) when searching history.

**Comment by robaxelsen** [comment]
@pablopunk Great, thanks! That was very helpful, and the bash reference list is awesome.
